Develop
mikethreels/nytimes-project pull request #9
Opened 2020-05-11 19:13 UTC by mikethreels

Changelog

- Added top navbar
- Added main paragraph section
- Added pictures
- Added video section
- Added aside section
- Added footer section

2020-05-11 22:36 UTC, addod19 commented
## Pull Request under review by Daniel Larbi Addo (TSE)

2020-05-11 22:55 UTC, addod19 requested changes
## Status: Require changes :recycle: :traffic_light: 

Hi, @mikethreels and @mimipeshy, great job on this project :+1: congratulations. Let us improve our code and make it better. Kindly find comments below: :smile: 

- The text should have a link, currently, it does not
![last](https://user-images.githubusercontent.com/46388113/81619056-4058c580-93d8-11ea-837d-bda670a64d66.png)
- Kindly add a detailed description to the README. You can check pathwright for the description, for example 'use float, flex, and grid to position elements.
- The live link is currently not working properly, kindly add more social handles to the author section
- Let us apply the DRY rule to our CSS file, so we avoid repeating code. This [article](https://speckyboy.com/good-bad-css-practices/)

KIndly make these changes and submit another code review :+1: 
_Happy coding_ :man_technologist: 
[Daniel Larbi Larbi](https://speckyboy.com/good-bad-css-practices/)

2020-05-11 22:55 UTC, addod19 commented on index.html
> +                    </div>
We could improve semantics by using ```<article>``` instead of ```< div class="topic-description">```

2020-05-12 17:36 UTC, mikethreels commented
Changelog
- updated hamburger button, search icon and the text in the navbar.
- updated more detailed README file.
- fixed the live link.
- cleaned up the CSS.
- replaced the `div class="topic-description"` to `article`

2020-05-13 00:09 UTC, lucasmazo32 approved these changes
# Project approved :rocket:

#### Great job on implementing the changes!

#### Your project looks great!

### You can go ahead and merge this pull request!

### Happy coding! :computer:

## Lucas Mazo

2020-05-13 06:53 UTC, merged